/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */




declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  TodoList as MyTodoList
} from './components/todo-list/todo-list';

declare global {
  interface HTMLMyTodoListElement extends MyTodoList, HTMLStencilElement {
  }
  var HTMLMyTodoListElement: {
    prototype: HTMLMyTodoListElement;
    new (): HTMLMyTodoListElement;
  };
  interface HTMLElementTagNameMap {
    "my-todo-list": HTMLMyTodoListElement;
  }
  interface ElementTagNameMap {
    "my-todo-list": HTMLMyTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-todo-list": JSXElements.MyTodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface MyTodoListAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  Todo as MyTodo
} from './components/todo/todo';

declare global {
  interface HTMLMyTodoElement extends MyTodo, HTMLStencilElement {
  }
  var HTMLMyTodoElement: {
    prototype: HTMLMyTodoElement;
    new (): HTMLMyTodoElement;
  };
  interface HTMLElementTagNameMap {
    "my-todo": HTMLMyTodoElement;
  }
  interface ElementTagNameMap {
    "my-todo": HTMLMyTodoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-todo": JSXElements.MyTodoAttributes;
    }
  }
  namespace JSXElements {
    export interface MyTodoAttributes extends HTMLAttributes {
      id?: string;
      value?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
