/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */




declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  TodoList as TodoList
} from './components/todo-list/todo-list';

declare global {
  interface HTMLTodoListElement extends TodoList, HTMLStencilElement {
  }
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };
  interface HTMLElementTagNameMap {
    "todo-list": HTMLTodoListElement;
  }
  interface ElementTagNameMap {
    "todo-list": HTMLTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "todo-list": JSXElements.TodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoListAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  Todo as MyTodo
} from './components/todo/todo';

declare global {
  interface HTMLMyTodoElement extends MyTodo, HTMLStencilElement {
  }
  var HTMLMyTodoElement: {
    prototype: HTMLMyTodoElement;
    new (): HTMLMyTodoElement;
  };
  interface HTMLElementTagNameMap {
    "my-todo": HTMLMyTodoElement;
  }
  interface ElementTagNameMap {
    "my-todo": HTMLMyTodoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-todo": JSXElements.MyTodoAttributes;
    }
  }
  namespace JSXElements {
    export interface MyTodoAttributes extends HTMLAttributes {
      id?: string;
      value?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
